[package]
name = "oxidation"
version = "0.1.0"
edition = "2024"
authors = ["rust Basel", "all its members"]


[dependencies]
axum = "0.8.4"
env_logger = "0.11.8"
log = "0.4.27"
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
